name: Deploy Bot

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI yt-dlp youtube-search-python google-api-python-client SpeechRecognition


      - name: Run bot
        run: |
          python bot.py
        env:
          BOT_TOKEN: ${{ secrets.Bot-token }}
          YTKEY: ${{ secrets.YTkey }}
